volumes:
  TTTDev:
  FastDL:

services:
  game:
    build: .
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      INSTALL_CSS: "true"
      SERVER_VOICE_ENABLE: 0
    volumes:
      - TTTDev:/home/steam/serverfiles
fastdl:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates
   - FastDL:/var/
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=fastdl.bxnto.de
   - NGINX_PORT=80
