volumes:
  TTTDev:

services:
  ttt:
    build: .
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    environment:
      INSTALL_CSS: "true"
      SERVER_DEFAULT_MAP: ttt_lttp_kakariko_a4
      SERVER_PORT: 27015
      SERVER_NAME: "Example Name"
      SERVER_PASSWORD: securePassword
      SERVER_VOICE_ENABLE: 0
      SERVER_MAX_PLAYERS: 20
      SERVER_RCON_PASSWORD: securePassword
      WORKSHOP_COLLECTION_ID: 1895900191
    volumes:
      - TTTDev:/home/steam/serverfiles
